"""Built-in German categorisation seed rules (data only).

Each rule maps a normalised payee/purpose pattern to an expense category.
Patterns are matched against the normalised payee+purpose; most match at a
word boundary (open-ended, so "mcdonald" also catches "MCDONALDS BERLIN"),
while short or common-word tokens listed in WHOLE_WORD_ONLY match only as a
complete word to avoid false positives. Order matters: the first matching
rule wins, so the disambiguation block is kept at the top.

Compiled from public brand/market research for the German market; user-
taught rules from the database always take precedence over these.
"""

from __future__ import annotations

SEED_RULES: list[tuple[str, str]] = [
    # --- Disambiguation / order-critical rules (must come first) ---
    ('amazon prime video', 'Streaming & Abos'),
    ('prime video', 'Streaming & Abos'),
    ('amazon music', 'Streaming & Abos'),
    ('amazon prime', 'Streaming & Abos'),
    ('apple com bill', 'Streaming & Abos'),
    ('apple music', 'Streaming & Abos'),
    ('apple tv', 'Streaming & Abos'),
    ('apple one', 'Streaming & Abos'),
    ('itunes', 'Streaming & Abos'),
    ('icloud', 'Streaming & Abos'),
    ('app store', 'Streaming & Abos'),
    ('apple store', 'Elektronik & Technik'),
    ('apple retail', 'Elektronik & Technik'),
    ('uber eats', 'Essen Bestellen & Fast Food'),
    ('ubereats', 'Essen Bestellen & Fast Food'),
    ('aldi talk', 'Telekommunikation'),
    ('aldi reisen', 'Reisen & Urlaub'),
    ('lidl connect', 'Telekommunikation'),
    ('lidl reisen', 'Reisen & Urlaub'),
    ('globus baumarkt', 'Haushalt & Möbel'),
    ('raiffeisenbank', 'Finanzen & Gebühren'),
    ('raiffeisen volksbank', 'Finanzen & Gebühren'),
    ('linkedin learning', 'Bildung'),
    # --- Lebensmittel ---
    ('edeka', 'Lebensmittel'),
    ('rewe', 'Lebensmittel'),
    ('aldi', 'Lebensmittel'),
    ('aldi nord', 'Lebensmittel'),
    ('lidl', 'Lebensmittel'),
    ('kaufland', 'Lebensmittel'),
    ('penny', 'Lebensmittel'),
    ('netto', 'Lebensmittel'),
    ('norma', 'Lebensmittel'),
    ('marktkauf', 'Lebensmittel'),
    ('famila', 'Lebensmittel'),
    ('combi', 'Lebensmittel'),
    ('tegut', 'Lebensmittel'),
    ('globus', 'Lebensmittel'),
    ('v markt', 'Lebensmittel'),
    ('nahkauf', 'Lebensmittel'),
    ('wasgau', 'Lebensmittel'),
    ('feneberg', 'Lebensmittel'),
    ('np markt', 'Lebensmittel'),
    ('denns', 'Lebensmittel'),
    ('alnatura', 'Lebensmittel'),
    ('bio company', 'Lebensmittel'),
    ('kamps', 'Lebensmittel'),
    ('backwerk', 'Lebensmittel'),
    ('back factory', 'Lebensmittel'),
    ('trinkgut', 'Lebensmittel'),
    ('fristo', 'Lebensmittel'),
    ('hol ab', 'Lebensmittel'),
    ('getranke hoffmann', 'Lebensmittel'),
    ('mix markt', 'Lebensmittel'),
    ('picnic', 'Lebensmittel'),
    ('rewe lieferservice', 'Lebensmittel'),
    ('bringmeister', 'Lebensmittel'),
    ('knuspr', 'Lebensmittel'),
    ('dursty', 'Lebensmittel'),
    ('getraenkeland', 'Lebensmittel'),
    ('flaschenpost', 'Lebensmittel'),
    ('zabka', 'Lebensmittel'),
    ('supermarkt', 'Lebensmittel'),
    ('lebensmittel', 'Lebensmittel'),
    ('wochenmarkt', 'Lebensmittel'),
    ('baeckerei', 'Lebensmittel'),
    ('backerei', 'Lebensmittel'),
    ('metzgerei', 'Lebensmittel'),
    ('getraenkemarkt', 'Lebensmittel'),
    ('getrankemarkt', 'Lebensmittel'),
    ('biomarkt', 'Lebensmittel'),
    ('hofladen', 'Lebensmittel'),
    # --- Essen Bestellen & Fast Food ---
    ('mcdonald', 'Essen Bestellen & Fast Food'),
    ('mcdonalds', 'Essen Bestellen & Fast Food'),
    ('burger king', 'Essen Bestellen & Fast Food'),
    ('kfc', 'Essen Bestellen & Fast Food'),
    ('kentucky fried chicken', 'Essen Bestellen & Fast Food'),
    ('subway', 'Essen Bestellen & Fast Food'),
    ('dominos', 'Essen Bestellen & Fast Food'),
    ('pizza hut', 'Essen Bestellen & Fast Food'),
    ('nordsee', 'Essen Bestellen & Fast Food'),
    ('five guys', 'Essen Bestellen & Fast Food'),
    ('call a pizza', 'Essen Bestellen & Fast Food'),
    ('hallo pizza', 'Essen Bestellen & Fast Food'),
    ('smiley', 'Essen Bestellen & Fast Food'),
    ('pizza max', 'Essen Bestellen & Fast Food'),
    ('wienerwald', 'Essen Bestellen & Fast Food'),
    ('lieferando', 'Essen Bestellen & Fast Food'),
    ('yourdelivery', 'Essen Bestellen & Fast Food'),
    ('just eat', 'Essen Bestellen & Fast Food'),
    ('wolt', 'Essen Bestellen & Fast Food'),
    ('flink', 'Essen Bestellen & Fast Food'),
    ('gorillas', 'Essen Bestellen & Fast Food'),
    ('getir', 'Essen Bestellen & Fast Food'),
    ('doner', 'Essen Bestellen & Fast Food'),
    ('doener', 'Essen Bestellen & Fast Food'),
    ('kebab', 'Essen Bestellen & Fast Food'),
    ('imbiss', 'Essen Bestellen & Fast Food'),
    ('dunkin', 'Essen Bestellen & Fast Food'),
    ('burgerme', 'Essen Bestellen & Fast Food'),
    ('fast food', 'Essen Bestellen & Fast Food'),
    ('schnellrestaurant', 'Essen Bestellen & Fast Food'),
    ('currywurst', 'Essen Bestellen & Fast Food'),
    ('lieferdienst', 'Essen Bestellen & Fast Food'),
    # --- Restaurant & Café ---
    ('starbucks', 'Restaurant & Café'),
    ('coffee fellows', 'Restaurant & Café'),
    ('espresso house', 'Restaurant & Café'),
    ('balzac', 'Restaurant & Café'),
    ('san francisco coffee', 'Restaurant & Café'),
    ('cafe extrablatt', 'Restaurant & Café'),
    ('l osteria', 'Restaurant & Café'),
    ('vapiano', 'Restaurant & Café'),
    ('block house', 'Restaurant & Café'),
    ('maredo', 'Restaurant & Café'),
    ('hans im gluck', 'Restaurant & Café'),
    ('sausalitos', 'Restaurant & Café'),
    ('cafe del sol', 'Restaurant & Café'),
    ('enchilada', 'Restaurant & Café'),
    ('mongos', 'Restaurant & Café'),
    ('marche', 'Restaurant & Café'),
    ('peter pane', 'Restaurant & Café'),
    ('hofbrauhaus', 'Restaurant & Café'),
    ('paulaner', 'Restaurant & Café'),
    ('ratskeller', 'Restaurant & Café'),
    ('brauhaus', 'Restaurant & Café'),
    ('eiscafe', 'Restaurant & Café'),
    ('gelateria', 'Restaurant & Café'),
    ('dean david', 'Restaurant & Café'),
    ('hard rock cafe', 'Restaurant & Café'),
    ('pizzeria', 'Restaurant & Café'),
    ('trattoria', 'Restaurant & Café'),
    ('osteria', 'Restaurant & Café'),
    ('comebuy', 'Restaurant & Café'),
    ('white lounge', 'Restaurant & Café'),
    ('hookah', 'Restaurant & Café'),
    ('foodji', 'Restaurant & Café'),
    ('restaurant', 'Restaurant & Café'),
    ('gaststaette', 'Restaurant & Café'),
    ('gaststatte', 'Restaurant & Café'),
    ('gasthaus', 'Restaurant & Café'),
    ('wirtshaus', 'Restaurant & Café'),
    ('bistro', 'Restaurant & Café'),
    ('ristorante', 'Restaurant & Café'),
    ('eisdiele', 'Restaurant & Café'),
    ('kaffeehaus', 'Restaurant & Café'),
    ('cafe', 'Restaurant & Café'),
    # --- Auto & Tanken ---
    ('aral', 'Auto & Tanken'),
    ('shell', 'Auto & Tanken'),
    ('esso', 'Auto & Tanken'),
    ('total', 'Auto & Tanken'),
    ('totalenergies', 'Auto & Tanken'),
    ('jet', 'Auto & Tanken'),
    ('hem', 'Auto & Tanken'),
    ('avia', 'Auto & Tanken'),
    ('omv', 'Auto & Tanken'),
    ('agip', 'Auto & Tanken'),
    ('eni', 'Auto & Tanken'),
    ('orlen', 'Auto & Tanken'),
    ('sprint', 'Auto & Tanken'),
    ('westfalen', 'Auto & Tanken'),
    ('bft', 'Auto & Tanken'),
    ('team tankstelle', 'Auto & Tanken'),
    ('classic tankstelle', 'Auto & Tanken'),
    ('tank rast', 'Auto & Tanken'),
    ('sanifair', 'Auto & Tanken'),
    ('atu', 'Auto & Tanken'),
    ('auto teile unger', 'Auto & Tanken'),
    ('pitstop', 'Auto & Tanken'),
    ('vergolst', 'Auto & Tanken'),
    ('euromaster', 'Auto & Tanken'),
    ('bosch car service', 'Auto & Tanken'),
    ('premio', 'Auto & Tanken'),
    ('first stop', 'Auto & Tanken'),
    ('point s', 'Auto & Tanken'),
    ('pneuhage', 'Auto & Tanken'),
    ('driver', 'Auto & Tanken'),
    ('quick reifen', 'Auto & Tanken'),
    ('autocrew', 'Auto & Tanken'),
    ('reifen com', 'Auto & Tanken'),
    ('mr wash', 'Auto & Tanken'),
    ('cleancar', 'Auto & Tanken'),
    ('imo car wash', 'Auto & Tanken'),
    ('reifen hahn', 'Auto & Tanken'),
    ('tesla', 'Auto & Tanken'),
    ('imoautopflege', 'Auto & Tanken'),
    ('imocarwash', 'Auto & Tanken'),
    ('easypark', 'Auto & Tanken'),
    ('mennekes', 'Auto & Tanken'),
    ('akyuerek', 'Auto & Tanken'),
    ('tankstelle', 'Auto & Tanken'),
    ('tanken', 'Auto & Tanken'),
    ('kraftstoff', 'Auto & Tanken'),
    ('autowerkstatt', 'Auto & Tanken'),
    ('kfz werkstatt', 'Auto & Tanken'),
    ('reifen', 'Auto & Tanken'),
    ('waschanlage', 'Auto & Tanken'),
    ('parkhaus', 'Auto & Tanken'),
    ('parkgebuehr', 'Auto & Tanken'),
    ('autogas', 'Auto & Tanken'),
    # --- Mobilität & ÖPNV ---
    ('deutsche bahn', 'Mobilität & ÖPNV'),
    ('db vertrieb', 'Mobilität & ÖPNV'),
    ('bahn de', 'Mobilität & ÖPNV'),
    ('db fernverkehr', 'Mobilität & ÖPNV'),
    ('db regio', 'Mobilität & ÖPNV'),
    ('bahncard', 'Mobilität & ÖPNV'),
    ('vbb', 'Mobilität & ÖPNV'),
    ('bvg', 'Mobilität & ÖPNV'),
    ('hvv', 'Mobilität & ÖPNV'),
    ('hochbahn', 'Mobilität & ÖPNV'),
    ('mvg', 'Mobilität & ÖPNV'),
    ('vrr', 'Mobilität & ÖPNV'),
    ('rmv', 'Mobilität & ÖPNV'),
    ('vvs', 'Mobilität & ÖPNV'),
    ('kvb', 'Mobilität & ÖPNV'),
    ('vrs', 'Mobilität & ÖPNV'),
    ('deutschlandticket', 'Mobilität & ÖPNV'),
    ('d ticket', 'Mobilität & ÖPNV'),
    ('flixbus', 'Mobilität & ÖPNV'),
    ('flixtrain', 'Mobilität & ÖPNV'),
    ('flix', 'Mobilität & ÖPNV'),
    ('free now', 'Mobilität & ÖPNV'),
    ('mytaxi', 'Mobilität & ÖPNV'),
    ('uber', 'Mobilität & ÖPNV'),
    ('bolt', 'Mobilität & ÖPNV'),
    ('taxi', 'Mobilität & ÖPNV'),
    ('miles', 'Mobilität & ÖPNV'),
    ('sixt share', 'Mobilität & ÖPNV'),
    ('sixt', 'Mobilität & ÖPNV'),
    ('share now', 'Mobilität & ÖPNV'),
    ('cambio', 'Mobilität & ÖPNV'),
    ('free2move', 'Mobilität & ÖPNV'),
    ('tier', 'Mobilität & ÖPNV'),
    ('lime', 'Mobilität & ÖPNV'),
    ('voi', 'Mobilität & ÖPNV'),
    ('dott', 'Mobilität & ÖPNV'),
    ('bird', 'Mobilität & ÖPNV'),
    ('bolt scooter', 'Mobilität & ÖPNV'),
    ('lufthansa', 'Mobilität & ÖPNV'),
    ('eurowings', 'Mobilität & ÖPNV'),
    ('ryanair', 'Mobilität & ÖPNV'),
    ('easyjet', 'Mobilität & ÖPNV'),
    ('condor', 'Mobilität & ÖPNV'),
    ('omio', 'Mobilität & ÖPNV'),
    ('trainline', 'Mobilität & ÖPNV'),
    ('nextbike', 'Mobilität & ÖPNV'),
    ('call a bike', 'Mobilität & ÖPNV'),
    ('monatsticket', 'Mobilität & ÖPNV'),
    ('fahrschein', 'Mobilität & ÖPNV'),
    ('fahrkarte', 'Mobilität & ÖPNV'),
    ('nahverkehr', 'Mobilität & ÖPNV'),
    ('verkehrsbetriebe', 'Mobilität & ÖPNV'),
    ('verkehrsverbund', 'Mobilität & ÖPNV'),
    ('carsharing', 'Mobilität & ÖPNV'),
    # --- Energie & Nebenkosten ---
    ('eon', 'Energie & Nebenkosten'),
    ('e on', 'Energie & Nebenkosten'),
    ('enbw', 'Energie & Nebenkosten'),
    ('vattenfall', 'Energie & Nebenkosten'),
    ('rwe', 'Energie & Nebenkosten'),
    ('ewe', 'Energie & Nebenkosten'),
    ('yello', 'Energie & Nebenkosten'),
    ('eprimo', 'Energie & Nebenkosten'),
    ('e wie einfach', 'Energie & Nebenkosten'),
    ('lichtblick', 'Energie & Nebenkosten'),
    ('naturstrom', 'Energie & Nebenkosten'),
    ('polarstern', 'Energie & Nebenkosten'),
    ('tibber', 'Energie & Nebenkosten'),
    ('octopus energy', 'Energie & Nebenkosten'),
    ('ostrom', 'Energie & Nebenkosten'),
    ('rabot', 'Energie & Nebenkosten'),
    ('awattar', 'Energie & Nebenkosten'),
    ('1komma5', 'Energie & Nebenkosten'),
    ('stromio', 'Energie & Nebenkosten'),
    ('grunwelt', 'Energie & Nebenkosten'),
    ('stadtwerke', 'Energie & Nebenkosten'),
    ('swm', 'Energie & Nebenkosten'),
    ('rheinenergie', 'Energie & Nebenkosten'),
    ('mainova', 'Energie & Nebenkosten'),
    ('enercity', 'Energie & Nebenkosten'),
    ('entega', 'Energie & Nebenkosten'),
    ('n ergie', 'Energie & Nebenkosten'),
    ('gasag', 'Energie & Nebenkosten'),
    ('badenova', 'Energie & Nebenkosten'),
    ('swk', 'Energie & Nebenkosten'),
    ('wasserbetriebe', 'Energie & Nebenkosten'),
    ('gelsenwasser', 'Energie & Nebenkosten'),
    ('hamburg wasser', 'Energie & Nebenkosten'),
    ('fernwarme', 'Energie & Nebenkosten'),
    ('stromnetz', 'Energie & Nebenkosten'),
    ('green planet energy', 'Energie & Nebenkosten'),
    ('stromrechnung', 'Energie & Nebenkosten'),
    ('gasanbieter', 'Energie & Nebenkosten'),
    ('energieversorgung', 'Energie & Nebenkosten'),
    ('fernwaerme', 'Energie & Nebenkosten'),
    ('wasserwerke', 'Energie & Nebenkosten'),
    # --- Telekommunikation ---
    ('telekom', 'Telekommunikation'),
    ('deutsche telekom', 'Telekommunikation'),
    ('magenta', 'Telekommunikation'),
    ('t mobile', 'Telekommunikation'),
    ('vodafone', 'Telekommunikation'),
    ('kabel deutschland', 'Telekommunikation'),
    ('o2', 'Telekommunikation'),
    ('telefonica', 'Telekommunikation'),
    ('1 1', 'Telekommunikation'),
    ('1 1 telecom', 'Telekommunikation'),
    ('1und1', 'Telekommunikation'),
    ('congstar', 'Telekommunikation'),
    ('otelo', 'Telekommunikation'),
    ('lebara', 'Telekommunikation'),
    ('winsim', 'Telekommunikation'),
    ('premiumsim', 'Telekommunikation'),
    ('sim de', 'Telekommunikation'),
    ('smartmobil', 'Telekommunikation'),
    ('simyo', 'Telekommunikation'),
    ('klarmobil', 'Telekommunikation'),
    ('fraenk', 'Telekommunikation'),
    ('freenet', 'Telekommunikation'),
    ('mobilcom debitel', 'Telekommunikation'),
    ('fyve', 'Telekommunikation'),
    ('drillisch', 'Telekommunikation'),
    ('pyur', 'Telekommunikation'),
    ('tele columbus', 'Telekommunikation'),
    ('m net', 'Telekommunikation'),
    ('netcologne', 'Telekommunikation'),
    ('netaachen', 'Telekommunikation'),
    ('ewe tel', 'Telekommunikation'),
    ('deutsche glasfaser', 'Telekommunikation'),
    ('tele2', 'Telekommunikation'),
    ('yourfone', 'Telekommunikation'),
    ('wilhelm tel', 'Telekommunikation'),
    ('ionos', 'Telekommunikation'),
    ('mobilfunk', 'Telekommunikation'),
    ('telekommunikation', 'Telekommunikation'),
    ('handytarif', 'Telekommunikation'),
    ('dsl', 'Telekommunikation'),
    ('festnetz', 'Telekommunikation'),
    # --- Streaming & Abos ---
    ('netflix', 'Streaming & Abos'),
    ('disney plus', 'Streaming & Abos'),
    ('disneyplus', 'Streaming & Abos'),
    ('wow', 'Streaming & Abos'),
    ('sky', 'Streaming & Abos'),
    ('dazn', 'Streaming & Abos'),
    ('paramount', 'Streaming & Abos'),
    ('magentatv', 'Streaming & Abos'),
    ('rtl plus', 'Streaming & Abos'),
    ('rtlplus', 'Streaming & Abos'),
    ('joyn', 'Streaming & Abos'),
    ('mubi', 'Streaming & Abos'),
    ('crunchyroll', 'Streaming & Abos'),
    ('spotify', 'Streaming & Abos'),
    ('deezer', 'Streaming & Abos'),
    ('youtube premium', 'Streaming & Abos'),
    ('youtube music', 'Streaming & Abos'),
    ('tidal', 'Streaming & Abos'),
    ('google one', 'Streaming & Abos'),
    ('google storage', 'Streaming & Abos'),
    ('dropbox', 'Streaming & Abos'),
    ('adobe', 'Streaming & Abos'),
    ('microsoft 365', 'Streaming & Abos'),
    ('office 365', 'Streaming & Abos'),
    ('onedrive', 'Streaming & Abos'),
    ('audible', 'Streaming & Abos'),
    ('patreon', 'Streaming & Abos'),
    ('twitch', 'Streaming & Abos'),
    ('linkedin', 'Streaming & Abos'),
    ('canva', 'Streaming & Abos'),
    ('nintendo switch online', 'Streaming & Abos'),
    ('storytel', 'Streaming & Abos'),
    ('sueddeutsche zeitung', 'Streaming & Abos'),
    ('zeit abo', 'Streaming & Abos'),
    ('spiegel plus', 'Streaming & Abos'),
    ('discord', 'Streaming & Abos'),
    ('streamingdienst', 'Streaming & Abos'),
    # --- Versicherung ---
    ('allianz', 'Versicherung'),
    ('huk coburg', 'Versicherung'),
    ('huk24', 'Versicherung'),
    ('huk', 'Versicherung'),
    ('axa', 'Versicherung'),
    ('ergo', 'Versicherung'),
    ('dkv', 'Versicherung'),
    ('debeka', 'Versicherung'),
    ('r v versicherung', 'Versicherung'),
    ('ruv', 'Versicherung'),
    ('generali', 'Versicherung'),
    ('gothaer', 'Versicherung'),
    ('provinzial', 'Versicherung'),
    ('signal iduna', 'Versicherung'),
    ('lvm', 'Versicherung'),
    ('vhv', 'Versicherung'),
    ('cosmosdirekt', 'Versicherung'),
    ('barmenia', 'Versicherung'),
    ('wurttembergische', 'Versicherung'),
    ('nurnberger', 'Versicherung'),
    ('continentale', 'Versicherung'),
    ('hannoversche', 'Versicherung'),
    ('wustenrot', 'Versicherung'),
    ('versicherungskammer', 'Versicherung'),
    ('alte leipziger', 'Versicherung'),
    ('hallesche', 'Versicherung'),
    ('devk', 'Versicherung'),
    ('zurich', 'Versicherung'),
    ('adac', 'Versicherung'),
    ('hdi', 'Versicherung'),
    ('arag', 'Versicherung'),
    ('ergo direkt', 'Versicherung'),
    ('concordia', 'Versicherung'),
    ('mecklenburgische', 'Versicherung'),
    ('inter versicherung', 'Versicherung'),
    ('versicherung', 'Versicherung'),
    ('krankenversicherung', 'Versicherung'),
    ('haftpflicht', 'Versicherung'),
    # --- Finanzen & Gebühren ---
    ('trade republic', 'Finanzen & Gebühren'),
    ('scalable', 'Finanzen & Gebühren'),
    ('comdirect', 'Finanzen & Gebühren'),
    ('flatex', 'Finanzen & Gebühren'),
    ('degiro', 'Finanzen & Gebühren'),
    ('justtrade', 'Finanzen & Gebühren'),
    ('finanzen net zero', 'Finanzen & Gebühren'),
    ('smartbroker', 'Finanzen & Gebühren'),
    ('etoro', 'Finanzen & Gebühren'),
    ('afterpay', 'Finanzen & Gebühren'),
    ('santander', 'Finanzen & Gebühren'),
    ('targobank', 'Finanzen & Gebühren'),
    ('targo', 'Finanzen & Gebühren'),
    ('swk bank', 'Finanzen & Gebühren'),
    ('bank11', 'Finanzen & Gebühren'),
    ('ikano', 'Finanzen & Gebühren'),
    ('consorsbank', 'Finanzen & Gebühren'),
    ('ing diba', 'Finanzen & Gebühren'),
    ('dkb', 'Finanzen & Gebühren'),
    ('n26', 'Finanzen & Gebühren'),
    ('tomorrow', 'Finanzen & Gebühren'),
    ('bunq', 'Finanzen & Gebühren'),
    ('revolut', 'Finanzen & Gebühren'),
    ('wise', 'Finanzen & Gebühren'),
    ('american express', 'Finanzen & Gebühren'),
    ('amex', 'Finanzen & Gebühren'),
    ('auxmoney', 'Finanzen & Gebühren'),
    ('smava', 'Finanzen & Gebühren'),
    ('younited', 'Finanzen & Gebühren'),
    ('postbank', 'Finanzen & Gebühren'),
    ('norisbank', 'Finanzen & Gebühren'),
    ('1822direkt', 'Finanzen & Gebühren'),
    ('bondora', 'Finanzen & Gebühren'),
    ('zinia', 'Finanzen & Gebühren'),
    ('rundfunkbeitrag', 'Finanzen & Gebühren'),
    ('ard zdf deutschlandradio', 'Finanzen & Gebühren'),
    ('bundeskasse', 'Finanzen & Gebühren'),
    ('transak', 'Finanzen & Gebühren'),
    ('kontofuehrung', 'Finanzen & Gebühren'),
    ('kontofuehrungsgebuehr', 'Finanzen & Gebühren'),
    ('bankgebuehr', 'Finanzen & Gebühren'),
    ('ratenkredit', 'Finanzen & Gebühren'),
    ('darlehen', 'Finanzen & Gebühren'),
    ('depotgebuehr', 'Finanzen & Gebühren'),
    # --- Drogerie & Körperpflege ---
    ('dm', 'Drogerie & Körperpflege'),
    ('dm drogerie', 'Drogerie & Körperpflege'),
    ('rossmann', 'Drogerie & Körperpflege'),
    ('mueller', 'Drogerie & Körperpflege'),
    ('muller', 'Drogerie & Körperpflege'),
    ('budni', 'Drogerie & Körperpflege'),
    ('budnikowsky', 'Drogerie & Körperpflege'),
    ('douglas', 'Drogerie & Körperpflege'),
    ('flaconi', 'Drogerie & Körperpflege'),
    ('notino', 'Drogerie & Körperpflege'),
    ('sephora', 'Drogerie & Körperpflege'),
    ('parfumdreams', 'Drogerie & Körperpflege'),
    ('pieper', 'Drogerie & Körperpflege'),
    ('parfumerie becker', 'Drogerie & Körperpflege'),
    ('akzente', 'Drogerie & Körperpflege'),
    ('lookfantastic', 'Drogerie & Körperpflege'),
    ('babor', 'Drogerie & Körperpflege'),
    ('yves rocher', 'Drogerie & Körperpflege'),
    ('body shop', 'Drogerie & Körperpflege'),
    ('rituals', 'Drogerie & Körperpflege'),
    ('lush', 'Drogerie & Körperpflege'),
    ('occitane', 'Drogerie & Körperpflege'),
    ('kiehls', 'Drogerie & Körperpflege'),
    ('mac cosmetics', 'Drogerie & Körperpflege'),
    ('klier', 'Drogerie & Körperpflege'),
    ('essanelle', 'Drogerie & Körperpflege'),
    ('super cut', 'Drogerie & Körperpflege'),
    ('klipp', 'Drogerie & Körperpflege'),
    ('marionnaud', 'Drogerie & Körperpflege'),
    ('beauty success', 'Drogerie & Körperpflege'),
    ('body and soul', 'Drogerie & Körperpflege'),
    ('drogerie', 'Drogerie & Körperpflege'),
    ('parfuemerie', 'Drogerie & Körperpflege'),
    ('parfumerie', 'Drogerie & Körperpflege'),
    ('friseur', 'Drogerie & Körperpflege'),
    ('kosmetikstudio', 'Drogerie & Körperpflege'),
    ('nagelstudio', 'Drogerie & Körperpflege'),
    # --- Gesundheit & Apotheke ---
    ('docmorris', 'Gesundheit & Apotheke'),
    ('shop apotheke', 'Gesundheit & Apotheke'),
    ('medpex', 'Gesundheit & Apotheke'),
    ('apotal', 'Gesundheit & Apotheke'),
    ('medikamente per klick', 'Gesundheit & Apotheke'),
    ('aliva', 'Gesundheit & Apotheke'),
    ('sanicare', 'Gesundheit & Apotheke'),
    ('mycare', 'Gesundheit & Apotheke'),
    ('apo rot', 'Gesundheit & Apotheke'),
    ('volksversand', 'Gesundheit & Apotheke'),
    ('eurapon', 'Gesundheit & Apotheke'),
    ('apotheke', 'Gesundheit & Apotheke'),
    ('fielmann', 'Gesundheit & Apotheke'),
    ('apollo', 'Gesundheit & Apotheke'),
    ('mister spex', 'Gesundheit & Apotheke'),
    ('pro optik', 'Gesundheit & Apotheke'),
    ('eyes more', 'Gesundheit & Apotheke'),
    ('brille24', 'Gesundheit & Apotheke'),
    ('optiker', 'Gesundheit & Apotheke'),
    ('kind hoergeraete', 'Gesundheit & Apotheke'),
    ('geers', 'Gesundheit & Apotheke'),
    ('amplifon', 'Gesundheit & Apotheke'),
    ('hoergeraete', 'Gesundheit & Apotheke'),
    ('zahnarzt', 'Gesundheit & Apotheke'),
    ('praxis', 'Gesundheit & Apotheke'),
    ('physiotherapie', 'Gesundheit & Apotheke'),
    ('aok', 'Gesundheit & Apotheke'),
    ('techniker krankenkasse', 'Gesundheit & Apotheke'),
    ('barmer', 'Gesundheit & Apotheke'),
    ('dak gesundheit', 'Gesundheit & Apotheke'),
    ('krankenkasse', 'Gesundheit & Apotheke'),
    ('arztpraxis', 'Gesundheit & Apotheke'),
    ('klinik', 'Gesundheit & Apotheke'),
    ('hoergerate', 'Gesundheit & Apotheke'),
    # --- Kleidung & Mode ---
    ('h m', 'Kleidung & Mode'),
    ('c und a', 'Kleidung & Mode'),
    ('zara', 'Kleidung & Mode'),
    ('bershka', 'Kleidung & Mode'),
    ('pull bear', 'Kleidung & Mode'),
    ('stradivarius', 'Kleidung & Mode'),
    ('massimo dutti', 'Kleidung & Mode'),
    ('primark', 'Kleidung & Mode'),
    ('peek cloppenburg', 'Kleidung & Mode'),
    ('peek und cloppenburg', 'Kleidung & Mode'),
    ('s oliver', 'Kleidung & Mode'),
    ('esprit', 'Kleidung & Mode'),
    ('tom tailor', 'Kleidung & Mode'),
    ('new yorker', 'Kleidung & Mode'),
    ('takko', 'Kleidung & Mode'),
    ('ernstings family', 'Kleidung & Mode'),
    ('kik', 'Kleidung & Mode'),
    ('nkd', 'Kleidung & Mode'),
    ('bonprix', 'Kleidung & Mode'),
    ('bonita', 'Kleidung & Mode'),
    ('orsay', 'Kleidung & Mode'),
    ('gerry weber', 'Kleidung & Mode'),
    ('mango', 'Kleidung & Mode'),
    ('uniqlo', 'Kleidung & Mode'),
    ('zalando', 'Kleidung & Mode'),
    ('about you', 'Kleidung & Mode'),
    ('shein', 'Kleidung & Mode'),
    ('asos', 'Kleidung & Mode'),
    ('temu', 'Kleidung & Mode'),
    ('boohoo', 'Kleidung & Mode'),
    ('vero moda', 'Kleidung & Mode'),
    ('jack jones', 'Kleidung & Mode'),
    ('engelhorn', 'Kleidung & Mode'),
    ('breuninger', 'Kleidung & Mode'),
    ('deichmann', 'Kleidung & Mode'),
    ('snipes', 'Kleidung & Mode'),
    ('gortz', 'Kleidung & Mode'),
    ('reno', 'Kleidung & Mode'),
    ('salamander', 'Kleidung & Mode'),
    ('mirapodo', 'Kleidung & Mode'),
    ('foot locker', 'Kleidung & Mode'),
    ('decathlon', 'Kleidung & Mode'),
    ('sportscheck', 'Kleidung & Mode'),
    ('intersport', 'Kleidung & Mode'),
    ('jd sports', 'Kleidung & Mode'),
    ('sport 2000', 'Kleidung & Mode'),
    ('nike', 'Kleidung & Mode'),
    ('adidas', 'Kleidung & Mode'),
    ('puma', 'Kleidung & Mode'),
    ('levis', 'Kleidung & Mode'),
    ('tommy hilfiger', 'Kleidung & Mode'),
    ('calvin klein', 'Kleidung & Mode'),
    ('hollister', 'Kleidung & Mode'),
    ('marc o polo', 'Kleidung & Mode'),
    ('street one', 'Kleidung & Mode'),
    ('cecil', 'Kleidung & Mode'),
    ('mode', 'Kleidung & Mode'),
    ('bekleidung', 'Kleidung & Mode'),
    ('schuhe', 'Kleidung & Mode'),
    ('modehaus', 'Kleidung & Mode'),
    # --- Elektronik & Technik ---
    ('mediamarkt', 'Elektronik & Technik'),
    ('media markt', 'Elektronik & Technik'),
    ('saturn', 'Elektronik & Technik'),
    ('expert', 'Elektronik & Technik'),
    ('euronics', 'Elektronik & Technik'),
    ('electronicpartner', 'Elektronik & Technik'),
    ('electronic partner', 'Elektronik & Technik'),
    ('medimax', 'Elektronik & Technik'),
    ('berlet', 'Elektronik & Technik'),
    ('expert klein', 'Elektronik & Technik'),
    ('cyberport', 'Elektronik & Technik'),
    ('notebooksbilliger', 'Elektronik & Technik'),
    ('alternate', 'Elektronik & Technik'),
    ('mindfactory', 'Elektronik & Technik'),
    ('coolblue', 'Elektronik & Technik'),
    ('conrad', 'Elektronik & Technik'),
    ('reichelt', 'Elektronik & Technik'),
    ('computeruniverse', 'Elektronik & Technik'),
    ('caseking', 'Elektronik & Technik'),
    ('pearl', 'Elektronik & Technik'),
    ('arlt', 'Elektronik & Technik'),
    ('csl computer', 'Elektronik & Technik'),
    ('jacob elektronik', 'Elektronik & Technik'),
    ('comtech', 'Elektronik & Technik'),
    ('samsung', 'Elektronik & Technik'),
    ('mediamarktsaturn', 'Elektronik & Technik'),
    ('gravis', 'Elektronik & Technik'),
    ('cyberport store', 'Elektronik & Technik'),
    ('sony store', 'Elektronik & Technik'),
    ('bose', 'Elektronik & Technik'),
    ('notebooksbilliger de', 'Elektronik & Technik'),
    ('galaxus', 'Elektronik & Technik'),
    ('computeruniverse de', 'Elektronik & Technik'),
    ('elektronik', 'Elektronik & Technik'),
    ('elektromarkt', 'Elektronik & Technik'),
    ('elektrofachmarkt', 'Elektronik & Technik'),
    # --- Haushalt & Möbel ---
    ('ikea', 'Haushalt & Möbel'),
    ('xxxlutz', 'Haushalt & Möbel'),
    ('momax', 'Haushalt & Möbel'),
    ('hoffner', 'Haushalt & Möbel'),
    ('mobel kraft', 'Haushalt & Möbel'),
    ('sconto', 'Haushalt & Möbel'),
    ('poco', 'Haushalt & Möbel'),
    ('roller', 'Haushalt & Möbel'),
    ('segmuller', 'Haushalt & Möbel'),
    ('mobel boss', 'Haushalt & Möbel'),
    ('porta', 'Haushalt & Möbel'),
    ('mobel martin', 'Haushalt & Möbel'),
    ('jysk', 'Haushalt & Möbel'),
    ('danisches bettenlager', 'Haushalt & Möbel'),
    ('pfister', 'Haushalt & Möbel'),
    ('home24', 'Haushalt & Möbel'),
    ('westwing', 'Haushalt & Möbel'),
    ('obi', 'Haushalt & Möbel'),
    ('bauhaus', 'Haushalt & Möbel'),
    ('hornbach', 'Haushalt & Möbel'),
    ('toom', 'Haushalt & Möbel'),
    ('hagebau', 'Haushalt & Möbel'),
    ('hellweg', 'Haushalt & Möbel'),
    ('werkers welt', 'Haushalt & Möbel'),
    ('dehner', 'Haushalt & Möbel'),
    ('pflanzen kolle', 'Haushalt & Möbel'),
    ('depot', 'Haushalt & Möbel'),
    ('nanu nana', 'Haushalt & Möbel'),
    ('butlers', 'Haushalt & Möbel'),
    ('action', 'Haushalt & Möbel'),
    ('tedi', 'Haushalt & Möbel'),
    ('woolworth', 'Haushalt & Möbel'),
    ('kodi', 'Haushalt & Möbel'),
    ('zeeman', 'Haushalt & Möbel'),
    ('mac geiz', 'Haushalt & Möbel'),
    ('hema', 'Haushalt & Möbel'),
    ('pfennigpfeiffer', 'Haushalt & Möbel'),
    ('thomas philipps', 'Haushalt & Möbel'),
    ('xenos', 'Haushalt & Möbel'),
    ('casa wohnen', 'Haushalt & Möbel'),
    ('zara home', 'Haushalt & Möbel'),
    ('maisons du monde', 'Haushalt & Möbel'),
    ('moebel', 'Haushalt & Möbel'),
    ('mobel', 'Haushalt & Möbel'),
    ('baumarkt', 'Haushalt & Möbel'),
    ('einrichtung', 'Haushalt & Möbel'),
    ('gartencenter', 'Haushalt & Möbel'),
    ('haushaltswaren', 'Haushalt & Möbel'),
    # --- Freizeit & Unterhaltung ---
    ('cinestar', 'Freizeit & Unterhaltung'),
    ('cinemaxx', 'Freizeit & Unterhaltung'),
    ('uci', 'Freizeit & Unterhaltung'),
    ('cineplex', 'Freizeit & Unterhaltung'),
    ('kinopolis', 'Freizeit & Unterhaltung'),
    ('cinemotion', 'Freizeit & Unterhaltung'),
    ('eventim', 'Freizeit & Unterhaltung'),
    ('ticketmaster', 'Freizeit & Unterhaltung'),
    ('reservix', 'Freizeit & Unterhaltung'),
    ('adticket', 'Freizeit & Unterhaltung'),
    ('eventbrite', 'Freizeit & Unterhaltung'),
    ('steam', 'Freizeit & Unterhaltung'),
    ('valve', 'Freizeit & Unterhaltung'),
    ('playstation', 'Freizeit & Unterhaltung'),
    ('psn', 'Freizeit & Unterhaltung'),
    ('xbox', 'Freizeit & Unterhaltung'),
    ('nintendo', 'Freizeit & Unterhaltung'),
    ('epic games', 'Freizeit & Unterhaltung'),
    ('mcfit', 'Freizeit & Unterhaltung'),
    ('john reed', 'Freizeit & Unterhaltung'),
    ('high5', 'Freizeit & Unterhaltung'),
    ('fitx', 'Freizeit & Unterhaltung'),
    ('clever fit', 'Freizeit & Unterhaltung'),
    ('korperformen', 'Freizeit & Unterhaltung'),
    ('fit plus', 'Freizeit & Unterhaltung'),
    ('bodystreet', 'Freizeit & Unterhaltung'),
    ('easyfitness', 'Freizeit & Unterhaltung'),
    ('fitness first', 'Freizeit & Unterhaltung'),
    ('elbgym', 'Freizeit & Unterhaltung'),
    ('urban sports club', 'Freizeit & Unterhaltung'),
    ('evo fitness', 'Freizeit & Unterhaltung'),
    ('europa park', 'Freizeit & Unterhaltung'),
    ('phantasialand', 'Freizeit & Unterhaltung'),
    ('heide park', 'Freizeit & Unterhaltung'),
    ('movie park', 'Freizeit & Unterhaltung'),
    ('legoland', 'Freizeit & Unterhaltung'),
    ('tropical islands', 'Freizeit & Unterhaltung'),
    ('guthaben de', 'Freizeit & Unterhaltung'),
    ('electronic arts', 'Freizeit & Unterhaltung'),
    ('g2a', 'Freizeit & Unterhaltung'),
    ('hellcase', 'Freizeit & Unterhaltung'),
    ('cs money', 'Freizeit & Unterhaltung'),
    ('iggm', 'Freizeit & Unterhaltung'),
    ('kino', 'Freizeit & Unterhaltung'),
    ('fitnessstudio', 'Freizeit & Unterhaltung'),
    ('fitness', 'Freizeit & Unterhaltung'),
    ('schwimmbad', 'Freizeit & Unterhaltung'),
    ('therme', 'Freizeit & Unterhaltung'),
    ('freizeitpark', 'Freizeit & Unterhaltung'),
    ('museum', 'Freizeit & Unterhaltung'),
    # --- Reisen & Urlaub ---
    ('booking', 'Reisen & Urlaub'),
    ('airbnb', 'Reisen & Urlaub'),
    ('expedia', 'Reisen & Urlaub'),
    ('hrs', 'Reisen & Urlaub'),
    ('trivago', 'Reisen & Urlaub'),
    ('edreams', 'Reisen & Urlaub'),
    ('opodo', 'Reisen & Urlaub'),
    ('hotels com', 'Reisen & Urlaub'),
    ('agoda', 'Reisen & Urlaub'),
    ('fewo direkt', 'Reisen & Urlaub'),
    ('vrbo', 'Reisen & Urlaub'),
    ('hometogo', 'Reisen & Urlaub'),
    ('interhome', 'Reisen & Urlaub'),
    ('novasol', 'Reisen & Urlaub'),
    ('tui', 'Reisen & Urlaub'),
    ('dertour', 'Reisen & Urlaub'),
    ('der touristik', 'Reisen & Urlaub'),
    ('alltours', 'Reisen & Urlaub'),
    ('schauinsland', 'Reisen & Urlaub'),
    ('fti', 'Reisen & Urlaub'),
    ('its reisen', 'Reisen & Urlaub'),
    ('urlaubsguru', 'Reisen & Urlaub'),
    ('holidaycheck', 'Reisen & Urlaub'),
    ('aida', 'Reisen & Urlaub'),
    ('mein schiff', 'Reisen & Urlaub'),
    ('motel one', 'Reisen & Urlaub'),
    ('b b hotels', 'Reisen & Urlaub'),
    ('premier inn', 'Reisen & Urlaub'),
    ('ibis', 'Reisen & Urlaub'),
    ('accor', 'Reisen & Urlaub'),
    ('mercure', 'Reisen & Urlaub'),
    ('novotel', 'Reisen & Urlaub'),
    ('nh hotel', 'Reisen & Urlaub'),
    ('leonardo hotel', 'Reisen & Urlaub'),
    ('maritim', 'Reisen & Urlaub'),
    ('best western', 'Reisen & Urlaub'),
    ('holiday inn', 'Reisen & Urlaub'),
    ('h hotels', 'Reisen & Urlaub'),
    ('marriott', 'Reisen & Urlaub'),
    ('hilton', 'Reisen & Urlaub'),
    ('steigenberger', 'Reisen & Urlaub'),
    ('center parcs', 'Reisen & Urlaub'),
    ('hotel de', 'Reisen & Urlaub'),
    ('hotel', 'Reisen & Urlaub'),
    ('reisebuero', 'Reisen & Urlaub'),
    ('pauschalreise', 'Reisen & Urlaub'),
    ('ferienwohnung', 'Reisen & Urlaub'),
    ('flug', 'Reisen & Urlaub'),
    ('airline', 'Reisen & Urlaub'),
    # --- Bildung ---
    ('udemy', 'Bildung'),
    ('coursera', 'Bildung'),
    ('skillshare', 'Bildung'),
    ('udacity', 'Bildung'),
    ('edx', 'Bildung'),
    ('babbel', 'Bildung'),
    ('duolingo', 'Bildung'),
    ('rosetta stone', 'Bildung'),
    ('busuu', 'Bildung'),
    ('pimsleur', 'Bildung'),
    ('studienkreis', 'Bildung'),
    ('schulerhilfe', 'Bildung'),
    ('gostudent', 'Bildung'),
    ('volkshochschule', 'Bildung'),
    ('vhs', 'Bildung'),
    ('sofatutor', 'Bildung'),
    ('preply', 'Bildung'),
    ('domestika', 'Bildung'),
    ('datacamp', 'Bildung'),
    ('masterclass', 'Bildung'),
    ('iversity', 'Bildung'),
    ('thalia', 'Bildung'),
    ('hugendubel', 'Bildung'),
    ('mayersche', 'Bildung'),
    ('online kurs', 'Bildung'),
    ('onlinekurs', 'Bildung'),
    ('nachhilfe', 'Bildung'),
    ('sprachkurs', 'Bildung'),
    ('studiengebuehr', 'Bildung'),
    ('seminar', 'Bildung'),
    ('weiterbildung', 'Bildung'),
    # --- Kinder & Familie ---
    ('mytoys', 'Kinder & Familie'),
    ('smyths toys', 'Kinder & Familie'),
    ('smythstoys', 'Kinder & Familie'),
    ('jako o', 'Kinder & Familie'),
    ('babyone', 'Kinder & Familie'),
    ('baby walz', 'Kinder & Familie'),
    ('babywalz', 'Kinder & Familie'),
    ('rofu', 'Kinder & Familie'),
    ('toys r us', 'Kinder & Familie'),
    ('kindergarten', 'Kinder & Familie'),
    ('spielwaren', 'Kinder & Familie'),
    ('kita', 'Kinder & Familie'),
    ('spielzeug', 'Kinder & Familie'),
    # --- Spenden ---
    ('unicef', 'Spenden'),
    ('aerzte ohne grenzen', 'Spenden'),
    ('arzte ohne grenzen', 'Spenden'),
    ('brot fuer die welt', 'Spenden'),
    ('caritas', 'Spenden'),
    ('diakonie', 'Spenden'),
    ('deutsches rotes kreuz', 'Spenden'),
    ('drk', 'Spenden'),
    ('wwf', 'Spenden'),
    ('greenpeace', 'Spenden'),
    ('misereor', 'Spenden'),
    ('sos kinderdorf', 'Spenden'),
    ('welthungerhilfe', 'Spenden'),
    ('plan international', 'Spenden'),
    ('tierschutz', 'Spenden'),
    ('tierheim', 'Spenden'),
    ('kirchensteuer', 'Spenden'),
    ('spende', 'Spenden'),
    ('wikimedia', 'Spenden'),
    ('foerderverein', 'Spenden'),
    ('hilfswerk', 'Spenden'),
    # --- Shopping & Online ---
    ('amazon', 'Shopping & Online'),
    ('amzn mktp', 'Shopping & Online'),
    ('amazon de', 'Shopping & Online'),
    ('ebay', 'Shopping & Online'),
    ('kleinanzeigen', 'Shopping & Online'),
    ('otto', 'Shopping & Online'),
    ('galeria', 'Shopping & Online'),
    ('karstadt', 'Shopping & Online'),
    ('kaufhof', 'Shopping & Online'),
    ('tchibo', 'Shopping & Online'),
    ('aliexpress', 'Shopping & Online'),
    ('wish', 'Shopping & Online'),
    ('etsy', 'Shopping & Online'),
    ('manufactum', 'Shopping & Online'),
    ('vinted', 'Shopping & Online'),
    ('wayfair', 'Shopping & Online'),
    ('limango', 'Shopping & Online'),
    ('qvc', 'Shopping & Online'),
    ('hse24', 'Shopping & Online'),
    ('klingel', 'Shopping & Online'),
    ('weltbild', 'Shopping & Online'),
    ('manomano', 'Shopping & Online'),
    ('rakuten', 'Shopping & Online'),
    # --- Wohnen & Miete ---
    ('vonovia', 'Wohnen & Miete'),
    ('deutsche wohnen', 'Wohnen & Miete'),
    ('leg immobilien', 'Wohnen & Miete'),
    ('grand city', 'Wohnen & Miete'),
    ('vivawest', 'Wohnen & Miete'),
    ('adler wohnen', 'Wohnen & Miete'),
    ('saga', 'Wohnen & Miete'),
    ('degewo', 'Wohnen & Miete'),
    ('gewobag', 'Wohnen & Miete'),
    ('howoge', 'Wohnen & Miete'),
    ('gesobau', 'Wohnen & Miete'),
    ('wbm', 'Wohnen & Miete'),
    ('stadt und land', 'Wohnen & Miete'),
    ('berlinovo', 'Wohnen & Miete'),
    ('gag immobilien', 'Wohnen & Miete'),
    ('gbg mannheim', 'Wohnen & Miete'),
    ('gwg', 'Wohnen & Miete'),
    ('muenchner wohnen', 'Wohnen & Miete'),
    ('aufbau dresden', 'Wohnen & Miete'),
    ('neue luebecker', 'Wohnen & Miete'),
    ('bauverein der elbgemeinden', 'Wohnen & Miete'),
    ('spar und bauverein', 'Wohnen & Miete'),
    ('wohnungsgenossenschaft', 'Wohnen & Miete'),
    ('baugenossenschaft', 'Wohnen & Miete'),
    ('hausverwaltung', 'Wohnen & Miete'),
    ('immobilienverwaltung', 'Wohnen & Miete'),
    ('hausgeld', 'Wohnen & Miete'),
    ('wohnungsgenossensch', 'Wohnen & Miete'),
    ('miete', 'Wohnen & Miete'),
    ('kaltmiete', 'Wohnen & Miete'),
    ('immobilien', 'Wohnen & Miete'),
    # --- Bargeld ---
    ('euronet', 'Bargeld'),
    ('cardpoint', 'Bargeld'),
    ('ic cash', 'Bargeld'),
    ('cardtronics', 'Bargeld'),
    ('cash group', 'Bargeld'),
    ('cashpool', 'Bargeld'),
    ('bargeldauszahlung', 'Bargeld'),
    ('geldautomat', 'Bargeld'),
    ('geldausgabeautomat', 'Bargeld'),
    ('abhebung', 'Bargeld'),
    ('atm', 'Bargeld'),
    ('bargeld', 'Bargeld'),
]

# Patterns that must match as a complete word (space padded) because they are
# short or coincide with common German words; matched open-ended otherwise.
WHOLE_WORD_ONLY: frozenset[str] = frozenset({
    '1 1',
    'action',
    'adac',
    'agip',
    'aida',
    'akzente',
    'aldi',
    'aliva',
    'amex',
    'aok',
    'apollo',
    'arag',
    'aral',
    'arlt',
    'asos',
    'atm',
    'atu',
    'avia',
    'axa',
    'bargeld',
    'bft',
    'bird',
    'block house',
    'bolt',
    'bose',
    'brauhaus',
    'bunq',
    'bvg',
    'cafe',
    'cecil',
    'combi',
    'condor',
    'conrad',
    'dazn',
    'denns',
    'depot',
    'devk',
    'dkb',
    'dkv',
    'dm',
    'dott',
    'driver',
    'drk',
    'dsl',
    'e on',
    'ebay',
    'edx',
    'enbw',
    'eni',
    'eon',
    'ergo',
    'esso',
    'etsy',
    'ewe',
    'expert',
    'fitx',
    'flink',
    'flix',
    'flug',
    'fti',
    'fyve',
    'g2a',
    'geers',
    'getir',
    'globus',
    'gwg',
    'h m',
    'hdi',
    'hem',
    'hema',
    'hol ab',
    'hrs',
    'huk',
    'hvv',
    'ibis',
    'ic cash',
    'iggm',
    'ikea',
    'imbiss',
    'jet',
    'joyn',
    'jysk',
    'kfc',
    'kik',
    'kino',
    'kita',
    'klingel',
    'klipp',
    'kodi',
    'kvb',
    'lidl',
    'lime',
    'lush',
    'lvm',
    'm net',
    'magenta',
    'mango',
    'marche',
    'miete',
    'miles',
    'mode',
    'mubi',
    'mueller',
    'muller',
    'mvg',
    'n26',
    'netto',
    'nike',
    'nkd',
    'nordsee',
    'norma',
    'np markt',
    'o2',
    'obi',
    'omio',
    'omv',
    'otelo',
    'otto',
    'pearl',
    'penny',
    'picnic',
    'poco',
    'point s',
    'porta',
    'premio',
    'psn',
    'puma',
    'pyur',
    'qvc',
    'reno',
    'rewe',
    'rmv',
    'rofu',
    'roller',
    'ruv',
    'rwe',
    'saga',
    'saturn',
    'sconto',
    'shell',
    'simyo',
    'sixt',
    'sky',
    'smiley',
    'steam',
    'stromnetz',
    'swk',
    'swm',
    'targo',
    'taxi',
    'tedi',
    'tele2',
    'temu',
    'tidal',
    'tier',
    'tomorrow',
    'toom',
    'total',
    'tui',
    'uber',
    'uci',
    'v markt',
    'vbb',
    'vhs',
    'vhv',
    'voi',
    'vrbo',
    'vrr',
    'vrs',
    'vvs',
    'wbm',
    'wise',
    'wish',
    'wolt',
    'wow',
    'wwf',
    'xbox',
    'zara',
})
